### PR TITLE
delay health checks until host has finished rebooting

### LINKED ISSUE #47: HTTP health checks can pass before the host has rebooted
Output from when using the `--reboot` flag of the `deploy` command.
```
Executing 'boot' on matched hosts:

** dhcp2036-p01

Asking host to reboot ... 
Running healthchecks on dhcp2036-p01:
	* Test Infestor is running: OK
	* Ask systemd whether there are failed or queued units.: Failed (Health check error: Failed to connect to bus: Broken pipe
Failed to connect to bus: Broken pipe
)
	* Test DHCP request using /nix/store/7dq9wap169g1dx8ssy2z0gxmmyrjrprw-check-dhcp: Failed (Health check error: Timeout after 5s)
```

The Infester check is HTTP based, while the others require SSH. Immediately after requesting a reboot, morph will start performing health checks, and it's pretty clear that a service can still be up at that point in time. We should implement some logic to check whether the host has rebooted, before running health checks.

### PR DESCRIPTION
**Pull request by adamtulinius**
This is implemented by getting the current boot ID, triggering reboot,
and then delaying health checks until the boot ID has changed.

Fixes #47

### CODE REVIEW

File: morph.go [hunk 1]
```diff
@@ -353,6 +354,20 @@ func execDeploy(hosts []nix.Host) (string, error) {
 		}
 
 		if deployReboot {
+			var (
```
Comment (johanot) [inline morph.go]: May I suggest extracting this entire `deployReboot`section to a separate functions, e.g. `deployReboot()`, since `execDeploy()` is becoming really big.

File: ssh/ssh.go [hunk 2]
```diff
@@ -237,6 +238,24 @@ func (ctx *SSHContext) ActivateConfiguration(host Host, configuration string, ac
...
 
+func (sshCtx *SSHContext) GetBootID(host Host) (string, error) {
+	ctx, cancel := context.WithTimeout(context.TODO(), 5 * time.Second)
+	defer cancel()
+	cmd, err := sshCtx.CmdContext(ctx, host, "cat", "/proc/sys/kernel/random/boot_id")
+	if err != nil {
+		return "", err
+	}
+
+	bytes, err := cmd.CombinedOutput()
```
Comment (johanot) [inline ssh/ssh.go]: Don't like `CombinedOutput()`. Outbursts from the ssh client like: `Warning: Permanently added <new-ip> to ssh known-hosts` end up in stderr - and thus in `bytes`, which has caused problems before when we depend on strict command output.

File: morph.go (hunk 1 above)
Comment (adamtulinius) [reply morph.go]: Sure, can do, totally reasonable.

File: ssh/ssh.go (hunk 2 above)
Comment (adamtulinius) [reply ssh/ssh.go]: Good point. Since it's difficult to combine redirecting stdout and stderr while also getting the output of the function, maybe we should transfer the file to localhost with scp instead?

File: morph.go (hunk 1 above)
Comment (adamtulinius) [reply morph.go]: Most of the current `execFoo` methods take a list of hosts to work on, so this could also be implementer as a method on the host interface.

File: ssh/ssh.go (hunk 2 above)
Comment (johanot) [reply ssh/ssh.go]: I guess you _could_ do that, but isn't this just a case where it's safer (and safe enough) to just read stdout and stderr into two different buffers, dump the former into `bytes` and dump the latter at morph stderr? I think we do something similar in other places.

File: morph.go (hunk 1 above)
Comment (johanot) [reply morph.go]: If it's too much of a pain to do, then don't. I just thought it would make `execDeploy` more readable. :)

Comment (adamtulinius) [reply morph.go]: It only depends on the SSHContext, so it's really easy to move around.

File: ssh/ssh.go (hunk 2 above)
Comment (adamtulinius) [reply ssh/ssh.go]: Sure. We can do that. However, I kinda feel it's really ugly to cat a file over SSH instead of just scp'ing it, although the latter requires temporary files, which is also _ick_.
